import { blank8843, visaYears } from '../src/utils/form8843Model.js'
export function sample8843() {
  return {
    ...blank8843(2025),
    firstName: 'Sample',
    lastName: 'Student',
    countryOfCitizenship: 'Nepal',
    passportCountry: 'Nepal',
    passportNumber: 'SAMPLE000',
    foreignAddress: 'Example Road, Kathmandu, Nepal',
    usStreet: '100 Example Street',
    usCity: 'Cypress',
    usState: 'CA',
    usZip: '90630',
    schoolName: 'Example College',
    schoolStreet: '200 Campus Avenue',
    schoolCity: 'Cypress',
    schoolState: 'CA',
    schoolZip: '90630',
    schoolPhone: '555-010-1234',
    dsoName: 'Sample Director',
    dsoStreet: '200 Campus Avenue',
    dsoCity: 'Cypress',
    dsoState: 'CA',
    dsoZip: '90630',
    dsoPhone: '555-010-1234',
    currentEntryDate: '08/20/2023',
    daysCurrent: '365',
    daysPrevious: '366',
    daysPrior: '134',
    daysToExclude: '365',
    line12Answer: 'no',
    line13Answer: 'no',
    visaHistory: Object.fromEntries(visaYears(2025).map((y) => [y, y < 2023 ? 'None' : 'F-1'])),
  }
}
