import { LegalLayout } from '../components/legal/LegalLayout'

const DISCLAIMER_CONTENT = {
  title: 'Disclaimer',
  lastUpdated: 'April 2026',
  intro: 'Please read this disclaimer carefully before using F1 Tax Helper.',
  sections: [
    {
      id: 'not-tax-advice',
      title: 'Not Professional Tax Advice',
      content:
        'F1 Tax Helper provides general educational information only and does not constitute tax, legal, or financial advice. Nothing in this service creates a tax-professional-client relationship. Always consult a qualified CPA or enrolled agent before filing.',
    },
    {
      id: 'ai-limitations',
      title: 'AI-Generated Content',
      content:
        'Responses are generated by AI and may not reflect the most current IRS rules or apply to your specific situation. Tax laws change frequently — always verify with irs.gov or a qualified tax professional.',
    },
    {
      id: 'no-guarantee',
      title: 'No Guarantee of Accuracy',
      content:
        'While we strive for accuracy, F1 Tax Helper makes no warranties about the completeness or reliability of any information. Use of this service is at your own risk.',
    },
    {
      id: 'irs-reference',
      title: 'IRS Resources',
      content:
        "For official guidance, refer to IRS Publication 519 (Tax Guide for Aliens) and IRS Publication 901 (U.S. Tax Treaties) at irs.gov. When in doubt, consult your university's International Student Office.",
    },
  ],
}

export default function Disclaimer() {
  return (
    <LegalLayout
      title={DISCLAIMER_CONTENT.title}
      lastUpdated={DISCLAIMER_CONTENT.lastUpdated}
      intro={DISCLAIMER_CONTENT.intro}
      sections={DISCLAIMER_CONTENT.sections}
    />
  )
}
