export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-background px-4 py-10">
      <div className="mx-auto max-w-3xl space-y-6">
        <h1 className="text-3xl font-bold tracking-tight text-foreground md:text-4xl">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground md:text-base">
          By using F1 Tax Helper, you agree that this tool is for educational
          and informational purposes only. It does not replace a qualified tax
          professional, enrolled agent, or CPA.
        </p>
        <p className="text-sm text-muted-foreground md:text-base">
          You are solely responsible for how you use the guidance generated by
          this app, including any tax forms you file or do not file. Always
          review your final tax return carefully before submitting it.
        </p>
        <p className="text-sm text-muted-foreground md:text-base">
          If you are unsure about your situation, you should speak with your
          university&apos;s international office or a qualified tax advisor
          before filing.
        </p>
      </div>
    </main>
  )
}

